spring.application.name=talentgrid-app

# logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
# logging.level.com.talentgrid.app=${LOG_LEVEL:INFO}

# spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:talentgridapp}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:none}

# spring.docker.compose.file=talentgrid-compose.yml

# spring.docker.compose.lifecycle-management=start-and-stop
# spring.docker.compose.start.command=up
# spring.docker.compose.stop.command=stop
